class NflCard extends HTMLElement {
  template = `
<div style="align-items:stretch;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width: 1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:300%;flex-direction:column;flex-grow:3;flex-shrink:1;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:86px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:482.469px;z-index:0;-webkit-box-align:stretch;-webkit-box-direction:normal;-webkit-box-flex 3;-webkit-box-orient:vertical;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
  <div style="align-items:center;background-color:rgb(255, 255, 255);border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:row;flex-shrink:0;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:70px;justify-content:space-between;line-height:19.6px;margin-bottom:8px;margin-left:0px;margin-right:0px;margin-top:8px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:482.469px;z-index:0;-webkit-box-align:center;-webkit-box-direction:normal;-webkit-box-orient:horizontal;-webkit-box-pack:justify;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
    <div style="align-items: stretch;border-bottom-color: rgb(0, 0, 0);border-bottom-style: solid;border-bottom-width: 0px;border-image-outset: 0;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-left-color: rgb(0, 0, 0);border-left-style: solid;border-left-width: 0px;border-right-color: rgb(0, 0, 0);border-right-style: solid;border-right-width: 0px;border-top-color: rgb(0, 0, 0);border-top-style: solid;border-top-width: 0px;box-sizing: border-box;color: rgb(51, 51, 51);cursor: pointer;display: flex;flex-basis: 100%;flex-direction: column;flex-grow: 1;flex-shrink: 1;font-family: All-ProSans-Light, sans-serif;font-size:14px;height:70px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:381.156px;z-index:0;-webkit-box-align:stretch;-webkit-box-direction:normal;-webkit-box-flex:1;-webkit-box-orient:vertical;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
      <div style="align-items:center;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:row;flex-shrink:0;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:35px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:381.156px;z-index:0;-webkit-box-align:center;-webkit-box-direction:normal;-webkit-box-orient:horizontal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
        <div style="align-items:center;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:column;flex-shrink:0;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:35px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;outline-color:rgb(51, 51, 51);outline-style:none;outline-width:0px;overflow-x:hidden;overflow-y:hidden;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:60.9844px;z-index:0;-webkit-box-align:center;-webkit-box-direction:normal;-webkit-box-orient:vertical;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
        <div style="align-items:stretch;background-color:rgba(0, 0, 0, 0);background-image:url(https://static.www.nfl.com/f_auto,q_auto/league/api/clubs/logos/{v});background-position-x:50%;background-position-y:50%;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:contain;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;bottom:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:column;flex-shrink:0;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:35px;left:0px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;outline-color:rgb(51, 51, 51);outline-style:none;outline-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:absolute;right:0px;text-size-adjust:100%;top:0px;user-select:none;width:60.9844px;z-index:-1;-webkit-box-align:stretch;-webkit-box-direction:normal;-webkit-box-orient:vertical;-webkit-font-smoothing antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);"></div>
        <img alt="" draggable="false" src="https://static.www.nfl.com/f_auto,q_auto/league/api/clubs/logos/{v}" style="order-bottom-color:rgb(51, 51, 51);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(51, 51, 51);border-left-style:none;border-left-width:0px;border-right-color:rgb(51, 51, 51);border-right-style:none;border-right-width:0px;border-top-color:rgb(51, 51, 51);border-top-style:none;border-top-width:0px;bottom:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:block;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:35px;left:0px;line-height:19.6px;max-width:100%;opacity:0;position:absolute;right:0px;text-size-adjust:100%;top:0px;user-select:none;width:60.9844px;z-index:-1;-webkit-box-direction:normal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);-webkit-user-drag:none;">
      </div>
      <div style="align-items:center;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:row;flex-grow:1;flex-shrink:1;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:19px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:268.438px;z-index:0;-webkit-box-align:center;-webkit-box-direction:normal;-webkit-box-flex:1;-webkit-box-orient:horizontal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
        <div dir="auto" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:block;font-family:All-ProSans-Medium;font-size:16px;font-stretch:100%;font-style:normal;font-variant-caps:normal;font-variant-east-asian:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-weight:400;height:19px;line-height:normal;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;overflow-wrap:break-word;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;unicode-bidi:isolate;user-select:none;white-space:pre-wrap;width:101.875px;-webkit-box-direction:normal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">{vnn}</div>
      </div>
      <div dir="auto" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:block;font-family:All-ProSans-Bold;font-size:18px;font-stretch:100%;font-style:normal;font-variant-caps:normal;font-variant-east-asian:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-weight:400;height:22px;line-height:normal;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;overflow-wrap:break-word;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-align:center;text-size-adjust:100%;unicode-bidi:isolate;user-select:none;white-space:pre-wrap;width:45.7344px;-webkit-box-direction:normal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">{vs}</div>
    </div>
    <div style="align-items: stretch;border-bottom-color: rgb(0, 0, 0);border-bottom-style: solid;border-bottom-width: 0px;border-image-outset: 0;border-image-repeat: stretch;border-image-slice: 100%;border-image-source: none;border-image-width: 1;border-left-color: rgb(0, 0, 0);border-left-style: solid;border-left-width: 0px;border-right-color: rgb(0, 0, 0);border-right-style: solid;border-right-width: 0px;border-top-color: rgb(0, 0, 0);border-top-style: solid;border-top-width: 0px;box-sizing: border-box;color: rgb(51, 51, 51);cursor: pointer;display: flex;flex-basis: 100%;flex-direction: column;flex-grow: 1;flex-shrink: 1;font-family: All-ProSans-Light, sans-serif;font-size:14px;height:70px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:381.156px;z-index:0;-webkit-box-align:stretch;-webkit-box-direction:normal;-webkit-box-flex:1;-webkit-box-orient:vertical;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
      <div style="align-items:center;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:row;flex-shrink:0;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:35px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:381.156px;z-index:0;-webkit-box-align:center;-webkit-box-direction:normal;-webkit-box-orient:horizontal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
        <div style="align-items:center;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:column;flex-shrink:0;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:35px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;outline-color:rgb(51, 51, 51);outline-style:none;outline-width:0px;overflow-x:hidden;overflow-y:hidden;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:60.9844px;z-index:0;-webkit-box-align:center;-webkit-box-direction:normal;-webkit-box-orient:vertical;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
        <div style="align-items:stretch;background-color:rgba(0, 0, 0, 0);background-image:url(https://static.www.nfl.com/f_auto,q_auto/league/api/clubs/logos/{h});background-position-x:50%;background-position-y:50%;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:contain;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;bottom:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:column;flex-shrink:0;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:35px;left:0px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;outline-color:rgb(51, 51, 51);outline-style:none;outline-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:absolute;right:0px;text-size-adjust:100%;top:0px;user-select:none;width:60.9844px;z-index:-1;-webkit-box-align:stretch;-webkit-box-direction:normal;-webkit-box-orient:vertical;-webkit-font-smoothing antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);"></div>
        <img alt="" draggable="false" src="https://static.www.nfl.com/f_auto,q_auto/league/api/clubs/logos/{h}" style="order-bottom-color:rgb(51, 51, 51);border-bottom-style:none;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(51, 51, 51);border-left-style:none;border-left-width:0px;border-right-color:rgb(51, 51, 51);border-right-style:none;border-right-width:0px;border-top-color:rgb(51, 51, 51);border-top-style:none;border-top-width:0px;bottom:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:block;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:35px;left:0px;line-height:19.6px;max-width:100%;opacity:0;position:absolute;right:0px;text-size-adjust:100%;top:0px;user-select:none;width:60.9844px;z-index:-1;-webkit-box-direction:normal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);-webkit-user-drag:none;">
      </div>
      <div style="align-items:center;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:row;flex-grow:1;flex-shrink:1;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:19px;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:268.438px;z-index:0;-webkit-box-align:center;-webkit-box-direction:normal;-webkit-box-flex:1;-webkit-box-orient:horizontal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">
        <div dir="auto" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:block;font-family:All-ProSans-Medium;font-size:16px;font-stretch:100%;font-style:normal;font-variant-caps:normal;font-variant-east-asian:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-weight:400;height:19px;line-height:normal;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;overflow-wrap:break-word;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-size-adjust:100%;unicode-bidi:isolate;user-select:none;white-space:pre-wrap;width:101.875px;-webkit-box-direction:normal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">{hnn}</div>
      </div>
      <div dir="auto" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:block;font-family:All-ProSans-Bold;font-size:18px;font-stretch:100%;font-style:normal;font-variant-caps:normal;font-variant-east-asian:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-weight:400;height:22px;line-height:normal;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;overflow-wrap:break-word;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;text-align:center;text-size-adjust:100%;unicode-bidi:isolate;user-select:none;white-space:pre-wrap;width:45.7344px;-webkit-box-direction:normal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">{hs}</div>
    </div>
  </div>
</div>
<div style="align-items:center;border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:flex;flex-basis:auto;flex-direction:column;flex-shrink:0;font-family:All-ProSans-Light, sans-serif;font-size:14px;height:70px;justify-content:center;line-height:19.6px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;min-height:0px;min-width:0px;padding-bottom:0px;padding-left:24.1094px;padding-right:0px;padding-top:0px;position:relative;text-size-adjust:100%;user-select:none;width:101.312px;z-index:0;-webkit-box-align:center;-webkit-box-direction:normal;-webkit-box-orient:vertical;-webkit-box-pack:center;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);background:blue">
<div dir="auto" style="border-bottom-color:rgb(0, 0, 0);border-bottom-style:solid;border-bottom-width:0px;border-image-outset:0;border-image-repeat:stretch;border-image-slice:100%;border-image-source:none;border-image-width:1;border-left-color:rgb(0, 0, 0);border-left-style:solid;border-left-width:0px;border-right-color:rgb(0, 0, 0);border-right-style:solid;border-right-width:0px;border-top-color:rgb(0, 0, 0);border-top-style:solid;border-top-width:0px;box-sizing:border-box;color:rgb(51, 51, 51);cursor:pointer;display:block;font-family:All-ProSans-Medium;font-size:12px;font-stretch:100%;font-style:normal;font-variant-caps:normal;font-variant-east-asian:normal;font-variant-ligatures:normal;font-variant-numeric:normal;font-weight:400;height:16px;line-height:16px;margin-bottom:0px;margin-left:0px;margin-right:0px;margin-top:0px;overflow-wrap:break-word;padding-bottom:0px;padding-left:4px;padding-right:0px;padding-top:0px;text-align:center;text-size-adjust:100%;unicode-bidi:isolate;user-select:none;white-space:pre-wrap;width:26.6875px;-webkit-box-direction:normal;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);">{q}</div>
</div>
  `;

  set hass(hass) {
    if (!this.content) {
      const card = document.createElement('ha-card');
      card.header = 'NFL Games of th day';
      this.content = document.createElement('div');
      this.content.style.padding = '0 16px 16px';
      card.appendChild(this.content);
      this.appendChild(card);
    }
    this.render();
  }

  render() {
    fetch('https://static.nfl.com/liveupdate/scorestrip/ss.json')
      .then((response) => {
        response.json().then((nfl_data) => {
          let c = '';
          for (let i = 0; i < nfl_data.gms.length;i++) {
            let t = this.template.replace('{vnn}', nfl_data.gms[i].vnn);
            t = t.replace('{hnn}', nfl_data.gms[i].hnn);
            t = t.replace('{v}', nfl_data.gms[i].v);
            t = t.replace('{h}', nfl_data.gms[i].h);
            t = t.replace('{vs}', nfl_data.gms[i].vs);
            t = t.replace('{hs}', nfl_data.gms[i].hs);
            t = t.replace('{q}', nfl_data.gms[i].q);
            c += t;
          }
          this.content.innerHTML = c;
        }).catch((error) => {
          console.error("Could not parse NFL Data!")
        });;
      }).catch((error) => {
        console.error("Could not load NFL Data!")
      });
      // JSON result in `data` variable
  }
  setConfig(e) {
    this.config = {}
  }
    
  // The height of your card. Home Assistant uses this to automatically
  // distribute all cards over the available columns.
  getCardSize() {
    return 3;
  }
}

customElements.define('nfl-card', NflCard);

console.info(
  '\n %c NFL Card %c v0.0.1 %c \n',
  'background-color: #555;color: #fff;padding: 3px 2px 3px 3px;border-radius: 3px 0 0 3px;font-family: DejaVu Sans,Verdana,Geneva,sans-serif;text-shadow: 0 1px 0 rgba(1, 1, 1, 0.3)',
  'background-color: #bc81e0;background-image: linear-gradient(90deg, #b65cff, #11cbfa);color: #fff;padding: 3px 3px 3px 2px;border-radius: 0 3px 3px 0;font-family: DejaVu Sans,Verdana,Geneva,sans-serif;text-shadow: 0 1px 0 rgba(1, 1, 1, 0.3)',
  'background-color: transparent'
);
